<a href="https://colab.research.google.com/github/Saransh-Basu-01/Natural-Language-Processing-NLP-/blob/main/N_grams.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
import pandas as pd

In [9]:
df=pd.DataFrame({'text':['people watch campusx','campusx watch campusx','people write comment','campusx write comment'],'labels':[1,1,0,0]})


In [10]:
df

,text,labels
0,people watch campusx,1
1,campusx watch campusx,1
2,people write comment,0
3,campusx write comment,0


In [11]:
from sklearn.feature_extraction.text import CountVectorizer

In [14]:
cv=CountVectorizer(ngram_range=(2,2))

In [15]:
bow=cv.fit_transform(df['text'])

In [17]:
cv.vocabulary_

{'people watch': 2,
 'watch campusx': 4,
 'campusx watch': 0,
 'people write': 3,
 'write comment': 5,
 'campusx write': 1}

In [18]:
bow[0].toarray()

array([[0, 0, 1, 0, 1, 0]])

In [19]:
cv.transform(['Helo campusx watch write campusx people helo helo']).toarray()

array([[1, 0, 0, 0, 0, 0]])

In [20]:
cv2=CountVectorizer(ngram_range=(1,2))

In [22]:
bow=cv2.fit_transform(df['text'])

In [23]:
cv2.vocabulary_

{'people': 4,
 'watch': 7,
 'campusx': 0,
 'people watch': 5,
 'watch campusx': 8,
 'campusx watch': 1,
 'write': 9,
 'comment': 3,
 'people write': 6,
 'write comment': 10,
 'campusx write': 2}

In [24]:
bow[0].toarray()

array([[1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0]])

In [26]:
cv2.transform(['Helo campusx watch write campusx people helo helo']).toarray()

array([[2, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0]])

In [27]:
cv3=CountVectorizer(ngram_range=(1,3))

In [28]:
bow=cv3.fit_transform(df['text'])

In [29]:
cv3.vocabulary_

{'people': 6,
 'watch': 11,
 'campusx': 0,
 'people watch': 7,
 'watch campusx': 12,
 'people watch campusx': 8,
 'campusx watch': 1,
 'campusx watch campusx': 2,
 'write': 13,
 'comment': 5,
 'people write': 9,
 'write comment': 14,
 'people write comment': 10,
 'campusx write': 3,
 'campusx write comment': 4}

In [30]:
cv4=CountVectorizer(ngram_range=(3,3))

In [31]:
bow=cv4.fit_transform(df['text'])

In [32]:
cv4.vocabulary_

{'people watch campusx': 2,
 'campusx watch campusx': 0,
 'people write comment': 3,
 'campusx write comment': 1}

In [35]:
cv5=CountVectorizer(ngram_range=(4,4))

In [36]:
bow=cv5.fit_transform(df['text'])

ValueError: empty vocabulary; perhaps the documents only contain stop words