<a href="https://colab.research.google.com/github/Saransh-Basu-01/Natural-Language-Processing-NLP-/blob/main/tfidf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
import pandas as pd

In [9]:
df=pd.DataFrame({'text':['people watch campusx','campusx watch campusx','people write comment','campusx write comment'],'labels':[1,1,0,0]})


In [10]:
df

,text,labels
0,people watch campusx,1
1,campusx watch campusx,1
2,people write comment,0
3,campusx write comment,0


In [37]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [38]:
tfidf=TfidfVectorizer()

In [39]:
tf=tfidf.fit_transform(df['text'])

In [40]:
tfidf.vocabulary_

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}

In [42]:
tf[0].toarray()

array([[0.49681612, 0.        , 0.61366674, 0.61366674, 0.        ]])

In [44]:
tfidf.transform(['Helo campusx watch write campusx people helo helo']).toarray()

array([[0.6829022 , 0.        , 0.42176004, 0.42176004, 0.42176004]])

In [46]:
tfidf.fit_transform(df['text']).toarray()

array([[0.49681612, 0.        , 0.61366674, 0.61366674, 0.        ],
       [0.8508161 , 0.        , 0.        , 0.52546357, 0.        ],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.57735027],
       [0.49681612, 0.61366674, 0.        , 0.        , 0.61366674]])